language: python
python:
  - "3.9"
install:
  - pip install -r requirements-dev.txt
script:
  - pip install -e .
  - pytest --cov=iqtrade
  - mypy iqtrade examples tests
  - flake8 iqtrade examples tests
  - black --diff --check iqtrade tests example
after_success:
  - codecov
