[tool.black]
line-length = 120
include = '\.py$'
target-version = ['py39']

[tool.isort]
line_length = 100
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
